// Bundled premium banner PNGs (generated by scripts/gen-banners.mjs, committed).
// The bot runtime only reads these files — no image libs at runtime.
const path = require("node:path");
const fss = require("node:fs");

const DIR = path.join(__dirname, "..", "assets");

function bannerPath(name) {
  const p = path.join(DIR, `${name}.png`);
  try {
    return fss.existsSync(p) ? p : null;
  } catch {
    return null;
  }
}

module.exports = {
  DIR,
  bannerPath,
  main: () => bannerPath("banner-main"),
  listing: () => bannerPath("banner-listing"),
  trending: () => bannerPath("banner-trending"),
};
