// Fourtis-style banner TEMPLATE compositor. An admin uploads a designed
// artwork (illustration/3D mascot/etc — the thing code can't draw) via
// @dexvraadminbot; every listing/trending channel post then composites the
// token's logo into the artwork's logo spot (circle-clipped) plus an optional
// $TICKER + name overlay. This is exactly how fourtis produces the banners the
// operator considers good — the art is designed once, the code only pastes.
//
// No template uploaded → compose() returns null and callers fall back to the
// programmatic dynamic banner (bannerRender.js). Never throws.
const path = require("node:path");
const fss = require("node:fs");
const os = require("node:os");
const { loadJSONSync, saveJSON, DATA_DIR } = require("./helpers/persist");
const { toSendBuffer } = require("./helpers/encodeImage");
const mediaMirror = require("./db/mediaMirror");
const log = require("./helpers/logger");
// The glyph guard. compose() is the ONE choke point every template overlay goes
// through — the pump alert reaches it via composeOntoClip — so the check lives
// here rather than at each caller.
const { warnBoxes, canvasLib, F } = require("./helpers/canvasKit");

const CONFIG_FILE = "bannerTemplate.json";
// Kinds with a bundled/uploadable STILL artwork (drives selfCheck + artwork API).
const KINDS = ["listing", "trending", "banner"];
// Every kind that carries a tunable layout — includes "pump", which is
// animation-only (composited onto its clip) and so has no bundled still art but
// still needs its saved position tweaks to load.
const LAYOUT_KINDS = ["listing", "trending", "banner", "pump"];
// Reference canvas — every layout coordinate in this module assumes this space.
const REF_W = 2560;
const REF_H = 1280;
// Admin-uploaded artwork (wins) lives in DATA_DIR; a bundled default artwork
// ships in assets/ (generated by scripts/gen-artwork.mjs) so banners look
// designed out-of-the-box. BANNER_BUNDLED_DIR is overridable for tests.
const uploadedPath = (kind) => path.join(DATA_DIR, `banner-template-${kind}.png`);
const BUNDLED_DIR = process.env.BANNER_BUNDLED_DIR || path.join(__dirname, "..", "assets");
const bundledPath = (kind) => path.join(BUNDLED_DIR, `banner-artwork-${kind}.png`);

const exists = (p) => {
  try {
    return fss.existsSync(p) && fss.statSync(p).size > 0;
  } catch {
    return false;
  }
};

/** "No coordinate stored" — the token name then follows the ticker (see
 *  nameX/nameY below). Not `!v`: 0 is a real coordinate (the left/top edge),
 *  and treating it as unset would make the one position an operator cannot
 *  choose the one they are most likely to want. */
const unset = (v) => v == null || v === "";

// ── Admin-uploaded GIF / VIDEO override (per kind) ───────────────────────────
// When set, the channel post uses this ANIMATED media instead of the composited
// still — a generic hype clip (the per-token details live in the caption, so
// nothing is composited into a video). Kind here is free-form (listing /
// trending / banner / pump) so pump alerts can carry a clip too.
//
// jpg/png are here for the group-alert kinds only (buy / whale / the ⭐ default
// slot), where the media is played AS-IS above a caption — a still house image
// is a legitimate choice there and used to be impossible: the upload accepted
// nothing but a clip, so an operator with artwork had to animate it first. The
// admin bot is what gates which kinds may take one; the compositing kinds
// (listing/trending/banner) still get their still artwork through the separate
// banner-template-<kind>.png upload, which is drawn on, not played.
const MEDIA_EXT = { gif: "animation", mp4: "video", webm: "video", mov: "video", jpg: "photo", png: "photo" };
let _mediaSeq = 0; // process-local counter → collision-free temp filenames on write
function mediaPath(kind, ext) {
  return path.join(DATA_DIR, `banner-media-${kind}.${ext}`);
}
/** { type: 'animation'|'video', source } for a kind's uploaded clip, or null.
 *  saveMedia keeps EXACTLY ONE clip file per kind, so normally there is a single
 *  candidate here. If a stale sibling of another extension ever lingers (a legacy
 *  upload from an older build, or a past removeMedia hiccup) it is SELF-HEALED:
 *  the most-recently-modified file wins and the strictly-older siblings are
 *  deleted, so an old clip can never win a future (possibly mtime-tied)
 *  comparison and resurrect itself — the root cause of "uploaded a new GIF but
 *  the preview still shows the old one". */
function mediaOverride(kind) {
  const found = [];
  for (const [ext, type] of Object.entries(MEDIA_EXT)) {
    const p = mediaPath(kind, ext);
    try {
      const st = fss.statSync(p);
      found.push({ type, source: p, mtimeMs: st.mtimeMs });
    } catch {
      /* not present */
    }
  }
  if (!found.length) return null;
  // Stable sort by mtime desc → newest first. Then drop any STRICTLY-OLDER
  // sibling (never a tie — deleting a tied file could drop the fresh upload).
  found.sort((a, b) => b.mtimeMs - a.mtimeMs);
  const best = found[0];
  for (const f of found) {
    if (f === best || f.mtimeMs >= best.mtimeMs) continue;
    try {
      fss.unlinkSync(f.source);
      log.info(`[bannerTpl] mediaOverride ${kind}: removed stale ${path.basename(f.source)} (older than ${path.basename(best.source)})`);
    } catch (e) {
      if (e && e.code !== "ENOENT") log.warn(`[bannerTpl] mediaOverride cleanup ${path.basename(f.source)}: ${e.message}`);
    }
  }
  return { type: best.type, source: best.source };
}
async function saveMedia(kind, buffer, ext) {
  const e = String(ext || "mp4").toLowerCase();
  if (!MEDIA_EXT[e]) throw new Error(`unsupported media type .${e} (use gif/mp4/webm/mov/jpg/png)`);
  await fss.promises.mkdir(DATA_DIR, { recursive: true });
  const outPath = mediaPath(kind, e);
  // Write the NEW clip FIRST, atomically (temp + rename). rename gives a clean
  // same-ext overwrite, and — because the new file is safely on disk BEFORE any
  // cleanup — a failed sibling delete can never leave the kind with no clip.
  const tmp = `${outPath}.${process.pid}.${_mediaSeq++}.tmp`;
  await fss.promises.writeFile(tmp, buffer);
  await fss.promises.rename(tmp, outPath);
  // Now drop EVERY other-extension sibling so exactly ONE clip exists per kind.
  // This is what actually kills "the old GIF still shows": if a prior upload
  // left, say, a banner-media-listing.gif behind and the admin now uploads an
  // .mp4, the stale .gif could otherwise win an mtime tie in mediaOverride. It
  // is removed here, AFTER the new file is durably written.
  for (const other of Object.keys(MEDIA_EXT)) {
    if (other === e) continue;
    await fss.promises.unlink(mediaPath(kind, other)).catch((err) => {
      if (err && err.code !== "ENOENT") log.warn(`[bannerTpl] saveMedia cleanup ${kind}.${other}: ${err.message}`);
    });
    mediaMirror.deleteMirror(path.basename(mediaPath(kind, other))).catch(() => {});
  }
  // Durable backup to Mongo (best-effort, fire-and-forget) so a container reset
  // restores the uploaded clip, not just the JSON config.
  mediaMirror.mirrorFile(path.basename(outPath)).catch(() => {});
  _invalidateClipCache(kind); // force the editor to re-extract a frame from the new clip
  // Loud diagnostic: shows the EXACT absolute path + byte count written, so a
  // wrong DATA_DIR / cwd (save landing somewhere the reader doesn't look) is obvious.
  log.info(`[bannerTpl] saveMedia ${kind}: wrote ${buffer.length}B → ${path.resolve(outPath)} (.${e}; siblings cleared)`);
  return { type: MEDIA_EXT[e], ext: e, bytes: buffer.length, path: path.resolve(outPath) };
}
async function removeMedia(kind) {
  for (const ext of Object.keys(MEDIA_EXT)) {
    try {
      await fss.promises.unlink(mediaPath(kind, ext));
    } catch (e) {
      // ENOENT = simply not present; anything else means a stale file may linger.
      if (e && e.code !== "ENOENT") log.warn(`[bannerTpl] removeMedia ${kind}.${ext}: ${e.message}`);
    }
    mediaMirror.deleteMirror(path.basename(mediaPath(kind, ext))).catch(() => {});
  }
  _invalidateClipCache(kind);
}
const hasMedia = (kind) => !!mediaOverride(kind);

// Defaults are tuned for the BUNDLED artworks (2560×1280). listing/trending:
// circular logo spot in the glowing ring + $TICKER/name under the status pill.
// banner (ads): a rectangular slot in the glass frame for the advertiser's
// creative, no text overlay (the creative speaks for itself).
const BASE_DEFAULTS = {
  slotShape: "circle", // "circle" (token logo) | "rect" (ad creative)
  logoSize: 420, // circle: diameter of the clipped logo
  logoX: 1890, // number | "center" — top-left of the slot
  logoY: 410,
  slotW: 1680, // rect: slot width/height
  slotH: 800,
  showText: true, // draw $TICKER + name overlay
  // Which meta chips to draw. Default: all three (chain · price · MC). A designed
  // template may want only some (e.g. trending shows chain only — the token's
  // name/$ticker already sit in its card).
  showChain: true,
  showPrice: true,
  showMcap: true,
  tickerFontSize: 96,
  tickerX: 210, // number | "center"
  tickerY: 618,
  tickerColor: "#FFFFFF",
  nameFontSize: 48,
  nameColor: "#B8CCC8",
  nameOffsetY: 96,
  // The token name FOLLOWS the ticker by default — same X, nameOffsetY below it
  // — which is what every layout tuned before these two keys existed relies on.
  // null means exactly that: "wherever the ticker is". The moment the operator
  // drags the name in the position editor these hold an absolute coordinate (or
  // "center") and the name stops following. Kept null-by-default rather than
  // seeded with a number so adding them changes NO existing banner: a default
  // coordinate would have teleported every tuned name to one spot.
  nameX: null,
  nameY: null,
  // token meta chips (CHAIN · price · MC) — auto-arranged as a row from metaX
  // (or centred), constant gap, each auto-sized to its text so they never
  // overflow or collide. Positioned & sized as a GROUP. X = LEFT edge / "center".
  metaX: 210,
  metaY: 772,
  metaFontSize: 34,
  // small badge on the glass pedestal under the ring (tier / trending duration).
  // Off by default — deployments with no tier system show no badge; turn it on
  // per-kind in the layout editor when a badge is wanted.
  showBadge: false,
  badgeX: 2100, // center x
  badgeY: 1002,
  badgeFontSize: 30,
};
const KIND_DEFAULTS = {
  // Listing keeps the token TEXT on the LEFT (its bundled art has an empty panel
  // there).
  listing: { ...BASE_DEFAULTS, tickerGlow: "#4EE6A8" },
  // Trending art puts a hero title ("Trending Alert") on the LEFT, so group the
  // token block on the RIGHT — under the logo ring — instead of over the title.
  // Deliberately DIFFERENT from listing (fine-tune per template in the layout /
  // position editor).
  trending: {
    ...BASE_DEFAULTS,
    tickerGlow: "#38D8F0",
    // Cyan $ticker + white name to match the trending template design.
    tickerColor: "#33E5C9",
    nameColor: "#EAF6F2",
    logoX: 1890,
    logoY: 350,
    logoSize: 430,
    // $ticker + name centred a bit more inside the right token card.
    tickerX: 1720,
    tickerY: 920,
    tickerFontSize: 80,
    nameFontSize: 44,
    nameOffsetY: 105,
    // Trending shows the CHAIN chip only — no price / MC — dropped into the
    // separate box at bottom-centre of the template (left of the token card).
    showPrice: false,
    showMcap: false,
    metaX: 1160,
    metaY: 1120,
    metaFontSize: 34,
  },
  // Pump alert art: a DISTINCT layout from listing/trending. Left card carries a
  // big "▲ +N%" headline, an "old → new" price line and a "MCAP $x" pill; the
  // token logo ring + cyan $ticker sit in the RIGHT card. Nothing here reuses the
  // listing/trending chip row — pump has its own overlay block below.
  pump: {
    ...BASE_DEFAULTS,
    tickerGlow: "#33E5C9",
    tickerColor: "#33E5C9",
    nameColor: "#EAF6F2",
    // Logo ring — right card.
    logoX: 1880,
    logoY: 360,
    logoSize: 420,
    // $ticker + name — centred under the right logo ring.
    tickerX: 1720,
    tickerY: 900,
    tickerFontSize: 84,
    nameFontSize: 44,
    nameOffsetY: 102,
    // The standard chain/price/MC chip row is OFF for pump — the pump overlay
    // draws its own %, price-transition and MCAP instead.
    showChain: false,
    showPrice: false,
    showMcap: false,
    // ▲ +N% headline (big, left card).
    pctX: 250,
    pctY: 545,
    pctFontSize: 172,
    pctColor: "#33E5C9",
    // old → new price transition (left card, under the %).
    priceX: 262,
    priceY: 762,
    priceFontSize: 78,
    // MCAP pill (left card, under the price). Reuses meta* so the position
    // editor's "Chips" handle drives it.
    metaX: 262,
    metaY: 902,
    metaFontSize: 44,
  },
  // slotFit "contain": the advertiser's whole creative is shown, never cropped.
  // See the fit block in compose() for why cover is wrong for paid artwork.
  banner: { ...BASE_DEFAULTS, slotShape: "rect", slotFit: "contain", logoX: 836, logoY: 296, slotW: 1548, slotH: 760, showText: false },
};
const defaultsFor = (kind) => KIND_DEFAULTS[kind] || BASE_DEFAULTS;
const DEFAULTS = BASE_DEFAULTS; // back-compat export

// Layout-version gate. updateSettings used to bake the ENTIRE then-current
// defaults into the saved file, so one ±20px tap froze every coordinate of
// that era's artwork forever — later default retunes could never win (live
// incident: ticker rendered at the bottom edge, empty text panel). Saved
// layouts now carry the version they were tuned against; a mismatch means
// "tuned for an older artwork" and the saved layout is ignored wholesale.
// Bump ONLY when the bundled artwork's layout changes (it invalidates saved
// admin tweaks by design — they were positioned against the old art).
const LAYOUT_VERSION = 6; // v6 artwork (gen-artwork.mjs)

function savedLayout(saved, kind) {
  const s = saved[kind];
  return s && s.layoutVersion === LAYOUT_VERSION ? s : {};
}

/** "600 × 240" → 2.5. The sold size string is the single source of truth for a
 *  banner's shape — the same string the website's tile aspect is keyed off — so
 *  the channel post and the homepage slot can never disagree about it.
 *  Anything unparseable returns 0, meaning "use the operator's box as drawn". */
function aspectOfSize(size) {
  const m = String(size || "").match(/(\d+)\s*[×x]\s*(\d+)/);
  if (!m) return 0;
  const w = Number(m[1]);
  const h = Number(m[2]);
  return w > 0 && h > 0 ? w / h : 0;
}

/** True once the operator has supplied their OWN artwork or clip for a kind. */
function isCustomArt(kind) {
  try {
    return hasUploaded(kind) || !!mediaOverride(kind);
  } catch {
    return false;
  }
}

function loadConfig() {
  const saved = loadJSONSync(CONFIG_FILE, {});
  const out = {};
  for (const k of LAYOUT_KINDS) {
    const base = defaultsFor(k);
    // The bundled artwork's slot coordinates are MEASURED against the bundled
    // artwork — the ad frame sits right of centre there, so logoX is 836. The
    // moment an operator uploads their own template we no longer know where its
    // frame is, and those coordinates become a wrong guess dressed as a default:
    // on a centred design the creative lands off to one side with dead space
    // beside it. Centre is the only defensible starting point for an unknown
    // design. Any explicit admin tweak still wins — this only fills the gap
    // where nothing has been tuned yet.
    const unknownDesign = base.slotShape === "rect" && isCustomArt(k);
    const start = unknownDesign ? { ...base, logoX: "center", logoY: "center" } : base;
    out[k] = { ...start, ...savedLayout(saved, k) };
  }
  return out;
}

// ── Global ON/OFF switch (admin-bot controlled, persisted) ──────────────────
// Lives in the config file under `_global` so operators flip it from
// @dexvraadminbot instead of fighting .env/PM2 env-snapshot semantics (live
// incident 2026-07-19: a stale POST_BANNERS=0 survived every restart). The
// POST_BANNERS env is only the DEFAULT when no admin choice was saved.
function postingEnabled() {
  const g = loadJSONSync(CONFIG_FILE, {})._global || {};
  // Default ON — banners are a core feature. ONLY an explicit admin toggle
  // (persisted _global.enabled === false in @dexvraadminbot) turns them off. A
  // stale POST_BANNERS=0 env snapshot must never silently kill every channel
  // banner again (recurring incident: "every announcement had no banner").
  if (typeof g.enabled === "boolean") return g.enabled;
  return true;
}
async function setPostingEnabled(on) {
  const saved = loadJSONSync(CONFIG_FILE, {});
  saved._global = { ...(saved._global || {}), enabled: !!on };
  await saveJSON(CONFIG_FILE, saved);
  return !!on;
}
async function updateSettings(kind, settings) {
  const saved = loadJSONSync(CONFIG_FILE, {});
  // persist ONLY the admin's tweaks (over prior same-version tweaks) — never
  // bake defaults in, so future default retunes flow through untouched keys
  saved[kind] = { ...savedLayout(saved, kind), ...settings, layoutVersion: LAYOUT_VERSION };
  await saveJSON(CONFIG_FILE, saved);
  return { ...defaultsFor(kind), ...saved[kind] };
}
/** Drop every saved tweak for a kind — back to the defaults tuned for the
 *  bundled artwork. Cure for stale coordinates saved against older layouts. */
async function resetSettings(kind) {
  const saved = loadJSONSync(CONFIG_FILE, {});
  if (kind in saved) {
    delete saved[kind];
    await saveJSON(CONFIG_FILE, saved);
  }
  return { ...defaultsFor(kind) };
}
function getSettings(kind) {
  return loadConfig()[kind] || { ...defaultsFor(kind) };
}

/** Resolve the artwork to composite: admin upload → bundled default → null. */
function resolvePath(kind) {
  if (exists(uploadedPath(kind))) return uploadedPath(kind);
  if (exists(bundledPath(kind))) return bundledPath(kind);
  return null;
}
const hasTemplate = (kind) => !!resolvePath(kind);
const hasUploaded = (kind) => exists(uploadedPath(kind));

// THE FONTS ARE canvasKit's, AND THAT IS THE WHOLE POINT.
//
// This module used to register Sora-800/600/500 under three private family
// names — TplBold / TplSemi / TplReg — and draw with `TplBold, sans-serif`.
// Those three files are Latin-only, so this renderer never reached the coverage
// chain at all: it was outside it, not last in it.
//
// That is why "$老昊" still shipped as "$□□" on the GIF overlay AFTER the
// fallback chain was built. Measured, with a CJK face registered process-wide:
//
//     "800 100px TplBold, sans-serif"   老昊 → 150   (notdef boxes)
//     "800 100px " + F.x                老昊 → 200   (real glyphs)
//
// Worse, it was SILENT. warnBoxes()/unrenderable() measure against F.r, so the
// guard was asking about a font stack this file did not use and answered "no
// missing glyphs" over a card that was drawing them — the one failure this
// whole area exists to make impossible. A guard is only honest while every
// renderer draws through the stack the guard measures.
//
// So there is ONE registration in this repo, in canvasKit, and compose() draws
// with F.x / F.s / F.m — the same Sora faces as before (Latin output is
// byte-identical), now carrying the CJK/Korean/Thai/Arabic/Devanagari/Hebrew
// tail every other renderer already had.

// Blend a hex colour toward white by `amt` (0..1) — used to give a coloured
// $ticker a subtle lighter-top gradient instead of a flat fill.
function lightenHex(hex, amt) {
  const n = parseInt(String(hex).replace("#", ""), 16);
  if (!Number.isFinite(n)) return hex;
  const r = (n >> 16) & 255,
    g = (n >> 8) & 255,
    b = n & 255;
  const L = (c) => Math.round(c + (255 - c) * amt);
  return `rgb(${L(r)},${L(g)},${L(b)})`;
}

/** Composite the kind's template with the token logo (+ optional text).
 *  Returns a PNG Buffer, or null when no template / any failure. */
async function compose(kind, logoBuffer, { symbol, name, chain, price, mcap, badge, change, priceFrom, priceTo, slotSize } = {}, opts = {}) {
  // `opts.transparent` renders ONLY the token overlay (logo + $ticker + name + chips +
  // badge) on a CLEAR canvas — used to composite that data onto an animated GIF/video
  // template. Otherwise this draws the still artwork background + the same overlay.
  const transparent = !!(opts && opts.transparent);
  warnBoxes(kind, { symbol, name });
  // Loud diagnostics: a null here silently downgrades channel posts to the raw
  // token logo, which reads as "the banner is broken" (live incident 2026-07).
  if (!transparent && !hasTemplate(kind)) {
    log.warn(`[bannerTpl] no '${kind}' artwork found (${uploadedPath(kind)} / ${bundledPath(kind)}) — posting without template`);
    return null;
  }
  const cv = canvasLib();
  if (!cv) {
    log.warn(`[bannerTpl] @napi-rs/canvas unavailable — run 'npm ci' in bot/ on the server, then restart`);
    return null;
  }
  try {
    const cfg = getSettings(kind);
    // ALWAYS compose on the 2560×1280 reference canvas so every layout coordinate
    // (tuned for 2560×1280) means the same thing regardless of the source size.
    const W = REF_W;
    const H = REF_H;
    const canvas = cv.createCanvas(W, H);
    const ctx = canvas.getContext("2d");
    if (!transparent) {
      const artPath = resolvePath(kind);
      if (!artPath) return null;
      const tpl = await cv.loadImage(artPath);
      ctx.drawImage(tpl, 0, 0, W, H);
    }

    // Media slot: token logo circle-clipped into the ring, or (banner ads)
    // the advertiser's creative cover-fitted into a rounded rectangular frame.
    const isRect = cfg.slotShape === "rect";
    // The box the operator drew is the BOUNDING area…
    const bw = isRect ? Number(cfg.slotW) || 1680 : Number(cfg.logoSize) || BASE_DEFAULTS.logoSize;
    const bh = isRect ? Number(cfg.slotH) || 800 : bw;
    const bx = cfg.logoX === "center" ? (W - bw) / 2 : Number(cfg.logoX) || 0;
    const by = cfg.logoY === "center" ? (H - bh) / 2 : Number(cfg.logoY) || 0;
    // …and the box actually drawn takes the SOLD shape of this booking, fitted
    // inside it and centred.
    //
    // A Standard Banner is sold at 600×240 (2.5:1) and a Wide at 1200×240
    // (5:1) — two different shapes, and neither is the frame's. With one fixed
    // box, an advertiser who sent exactly what we asked for still could not
    // fill it: either the sides were cropped, or a blurred band appeared above
    // and below. Drawing the box at the shape we sold means a correct upload
    // lands edge to edge, with nothing cropped and nothing filled in, for both
    // products. An off-spec upload still falls back to the fit rule below.
    let sw = bw;
    let sh = bh;
    const soldAspect = isRect ? aspectOfSize(slotSize) : 0;
    if (soldAspect > 0) {
      if (bw / bh > soldAspect) sw = Math.round(bh * soldAspect);
      else sh = Math.round(bw / soldAspect);
    }
    const lx = bx + (bw - sw) / 2;
    const ly = by + (bh - sh) / 2;
    if (logoBuffer) {
      try {
        const img = await cv.loadImage(logoBuffer);
        ctx.save();
        ctx.beginPath();
        if (isRect) {
          const r = Math.min(40, sw / 2, sh / 2);
          ctx.moveTo(lx + r, ly);
          ctx.arcTo(lx + sw, ly, lx + sw, ly + sh, r);
          ctx.arcTo(lx + sw, ly + sh, lx, ly + sh, r);
          ctx.arcTo(lx, ly + sh, lx, ly, r);
          ctx.arcTo(lx, ly, lx + sw, ly, r);
        } else {
          ctx.arc(lx + sw / 2, ly + sh / 2, sw / 2, 0, Math.PI * 2);
        }
        ctx.closePath();
        ctx.clip();
        // How a picture whose shape differs from the box is fitted.
        //
        //   cover   — scale until the box is full, crop what sticks out.
        //   contain — scale until the whole picture fits, fill the gap with a
        //             blurred, dimmed copy of itself so it reads as design.
        //
        // A token logo is cover-fitted: it is a square in a circle, nothing is
        // lost. An ADVERTISER'S CREATIVE is not. Cover was cutting paid artwork
        // to pieces — a Wide Banner is sold at 1200×240 (5:1) and the frame is
        // 1548×760 (2:1), so cover threw away 59% of its WIDTH: the buyer paid
        // for a banner and roughly its middle third was published. contain is
        // therefore the default for a rectangular (ad) slot, and an operator who
        // wants edge-to-edge fill can still choose cover per service.
        const fit = isRect ? (cfg.slotFit === "cover" ? "cover" : "contain") : "cover";
        const place = (scale) => {
          const w = img.width * scale;
          const h = img.height * scale;
          ctx.drawImage(img, lx + sw / 2 - w / 2, ly + sh / 2 - h / 2, w, h);
        };
        if (fit === "contain") {
          // Backdrop first: the same picture, blown up to fill and blurred, so
          // the letterbox gap is never a flat black bar.
          ctx.save();
          ctx.filter = "blur(28px)";
          ctx.globalAlpha = 0.5;
          place(Math.max(sw / img.width, sh / img.height));
          ctx.restore();
          // Then the creative itself, whole and uncropped.
          place(Math.min(sw / img.width, sh / img.height));
        } else {
          place(Math.max(sw / img.width, sh / img.height));
        }
        ctx.restore();
        if (!isRect) {
          ctx.beginPath();
          ctx.arc(lx + sw / 2, ly + sh / 2, sw / 2 + 2, 0, Math.PI * 2);
          ctx.strokeStyle = "rgba(255,255,255,.55)";
          ctx.lineWidth = 3;
          ctx.stroke();
        }
      } catch (e) {
        log.debug(`[bannerTpl] media overlay: ${e.message}`); // artwork still posts
      }
    }

    // $TICKER + name overlay (position/size admin-tunable; off if artwork has
    // its own text or the admin prefers the art clean). Ticker renders with a
    // vertical white→tint gradient + soft accent glow — jewelry, not print.
    if (cfg.showText && symbol) {
      const ticker = `$${String(symbol).replace(/^\$+/, "").toUpperCase()}`;
      const fsz = Number(cfg.tickerFontSize) || 96;
      ctx.textBaseline = "middle";
      ctx.font = `800 ${fsz}px ${F.x}`;
      const tw = ctx.measureText(ticker).width;
      const tx = cfg.tickerX === "center" ? (W - tw) / 2 : Number(cfg.tickerX) || 0;
      const ty = cfg.tickerY === "center" ? H / 2 : Number(cfg.tickerY) || 0;
      // soft accent glow pass
      const glow = cfg.tickerGlow || "#4EE6A8";
      ctx.shadowColor = glow + "66";
      ctx.shadowBlur = Math.max(18, fsz * 0.3);
      ctx.shadowOffsetY = 0;
      const tc = cfg.tickerColor || "#FFFFFF";
      const grad = ctx.createLinearGradient(0, ty - fsz * 0.55, 0, ty + fsz * 0.45);
      if (tc.toUpperCase() === "#FFFFFF") {
        // White ticker (listing default): keep the crisp white→mint sheen.
        grad.addColorStop(0, "#FFFFFF");
        grad.addColorStop(0.72, "#FFFFFF");
        grad.addColorStop(1, "#BFE9DC");
      } else {
        // Coloured ticker (e.g. trending cyan): a lighter top → the colour, so it
        // reads as that colour, not white with a tint.
        grad.addColorStop(0, lightenHex(tc, 0.55));
        grad.addColorStop(1, tc);
      }
      ctx.fillStyle = grad;
      ctx.fillText(ticker, tx, ty);
      // crisp second pass (kills glow muddiness on the glyph body)
      ctx.shadowColor = "rgba(0,0,0,.55)";
      ctx.shadowBlur = 6;
      ctx.shadowOffsetY = 2;
      ctx.fillText(ticker, tx, ty);
      if (name) {
        ctx.shadowColor = "rgba(0,0,0,.6)";
        ctx.shadowBlur = 6;
        ctx.shadowOffsetY = 2;
        ctx.font = `500 ${cfg.nameFontSize}px ${F.m}`;
        ctx.fillStyle = cfg.nameColor;
        // Measure the string that is actually DRAWN. Measuring the full name and
        // drawing a 32-char slice put a long centred name off-centre by exactly
        // the width of the text that got cut.
        const label = String(name).slice(0, 32);
        const nameW = ctx.measureText(label).width;
        // An explicit nameX/nameY wins; unset, the name follows the ticker.
        const nx = unset(cfg.nameX)
          ? cfg.tickerX === "center"
            ? (W - nameW) / 2
            : tx
          : cfg.nameX === "center"
            ? (W - nameW) / 2
            : Number(cfg.nameX) || 0;
        const ny = unset(cfg.nameY) ? ty + Number(cfg.nameOffsetY) : cfg.nameY === "center" ? H / 2 : Number(cfg.nameY) || 0;
        ctx.fillText(label, nx, ny);
      }
      ctx.shadowColor = "transparent";
      ctx.shadowBlur = 0;
      ctx.shadowOffsetY = 0;
    }

    // Token meta chips under the ring — CHAIN / price / market cap, each drawn
    // arranged as a ROW from metaX with a constant gap, each pill auto-sized to
    // its text. This never overflows or collides no matter how long the price is.
    if (cfg.showText && cfg.slotShape !== "rect" && kind !== "pump") {
      const tint = (cfg.tickerGlow || "#4EE6A8") + "55";
      const fsz = Number(cfg.metaFontSize) || 34;
      const chipH = fsz * 1.9;
      const r = Math.min(chipH / 2, fsz * 0.55); // gentle rounded-rect corners
      const padX = fsz * 0.62; // snug, balanced padding — box hugs the text
      const gap = Math.round(fsz * 0.5);
      const cy = Number(cfg.metaY) || H - 152;
      ctx.font = `600 ${fsz}px ${F.s}`;
      const vals = [
        cfg.showChain === false ? null : chain,
        cfg.showPrice === false ? null : price && price !== "TBA" ? price : null,
        cfg.showMcap === false ? null : mcap ? `MC ${mcap}` : null,
      ]
        .filter(Boolean)
        .map(String);
      const widths = vals.map((t) => ctx.measureText(t).width + padX * 2);
      const total = widths.reduce((a, b) => a + b, 0) + gap * Math.max(0, vals.length - 1);
      let x = cfg.metaX === "center" ? (W - total) / 2 : Number(cfg.metaX) || 210;
      ctx.textAlign = "center"; // centred text → balanced padding, and any measure
      ctx.textBaseline = "middle"; // slack is split evenly instead of piling up on one side
      for (let i = 0; i < vals.length; i++) {
        const t = vals[i];
        const w = widths[i];
        ctx.beginPath();
        ctx.moveTo(x + r, cy);
        ctx.arcTo(x + w, cy, x + w, cy + chipH, r);
        ctx.arcTo(x + w, cy + chipH, x, cy + chipH, r);
        ctx.arcTo(x, cy + chipH, x, cy, r);
        ctx.arcTo(x, cy, x + w, cy, r);
        ctx.closePath();
        ctx.fillStyle = "rgba(255,255,255,.055)";
        ctx.fill();
        ctx.lineWidth = 2;
        ctx.strokeStyle = tint;
        ctx.stroke();
        ctx.fillStyle = i === 0 ? "#EAF6F2" : "#CFE4DE";
        ctx.fillText(t, x + w / 2, cy + chipH / 2 + 2);
        x += w + gap;
      }
      ctx.textAlign = "left";
      ctx.textBaseline = "alphabetic";
    }

    // Pump-alert overlay — a DISTINCT left-card block (▲ +N% headline · old→new
    // price transition · MCAP pill) that replaces the standard chip row. change /
    // priceFrom / priceTo come from the pump checker; each part degrades gracefully
    // if its datum is missing, so a partial pump still renders cleanly.
    if (kind === "pump" && cfg.showText) {
      const accent = cfg.pctColor || cfg.tickerColor || "#33E5C9";
      // ▲ +N% headline. The ▲ is drawn as a VECTOR triangle — the bundled Sora
      // fonts have no ▲/→ glyphs (they'd render as tofu ▯), so every symbol here
      // is a shape, never a character.
      if (change != null && String(change).trim() !== "") {
        let body = String(change).trim().replace(/^[▲▼]\s*/, "");
        if (!/^[+\-]/.test(body)) body = `+${body}`;
        const pfs = Number(cfg.pctFontSize) || 172;
        const centered = cfg.pctX === "center";
        const py = Number(cfg.pctY) || 545;
        ctx.font = `800 ${pfs}px ${F.x}`;
        ctx.textBaseline = "middle";
        const triW = pfs * 0.6; // up-triangle bounding box
        const triH = pfs * 0.54;
        const triGap = pfs * 0.24;
        const textW = ctx.measureText(body).width;
        const groupW = triW + triGap + textW;
        const startX = centered ? W / 2 - groupW / 2 : Number(cfg.pctX) || 250;
        const grad = ctx.createLinearGradient(0, py - pfs * 0.5, 0, py + pfs * 0.5);
        grad.addColorStop(0, lightenHex(accent, 0.5));
        grad.addColorStop(1, accent);
        // filled up-triangle (glow pass folded into the same fill)
        ctx.save();
        ctx.shadowColor = accent + "66";
        ctx.shadowBlur = Math.max(20, pfs * 0.28);
        ctx.fillStyle = grad;
        const tcx = startX + triW / 2;
        const tTop = py - triH / 2;
        const tBot = py + triH / 2;
        const rr = triH * 0.12; // slightly rounded apex/corners
        ctx.beginPath();
        ctx.moveTo(tcx, tTop);
        ctx.lineTo(startX + triW - rr, tBot);
        ctx.lineTo(startX + rr, tBot);
        ctx.closePath();
        ctx.fill();
        ctx.restore();
        // the +N% text
        ctx.textAlign = "left";
        const textX = startX + triW + triGap;
        ctx.shadowColor = accent + "66";
        ctx.shadowBlur = Math.max(20, pfs * 0.28);
        ctx.shadowOffsetY = 0;
        ctx.fillStyle = grad;
        ctx.fillText(body, textX, py);
        ctx.shadowColor = "rgba(0,0,0,.5)";
        ctx.shadowBlur = 6;
        ctx.shadowOffsetY = 2;
        ctx.fillText(body, textX, py);
        ctx.shadowColor = "transparent";
        ctx.shadowBlur = 0;
        ctx.shadowOffsetY = 0;
      }
      // old → new price transition (dim old · vector arrow · bright new)
      const from = priceFrom && priceFrom !== "TBA" ? String(priceFrom) : null;
      const to = priceTo && priceTo !== "TBA" ? priceTo : price && price !== "TBA" ? price : null;
      if (to) {
        const rfs = Number(cfg.priceFontSize) || 78;
        const rx = cfg.priceX === "center" ? W / 2 : Number(cfg.priceX) || 262;
        const ry = Number(cfg.priceY) || 762;
        ctx.font = `700 ${rfs}px ${F.x}`;
        ctx.textAlign = "left";
        ctx.textBaseline = "middle";
        const arrowW = rfs * 0.9; // width the vector "→" occupies
        const gapw = rfs * 0.3;
        // Pre-measure so a centred priceX keeps the whole line centred.
        const fromW = from ? ctx.measureText(from).width : 0;
        const toW = ctx.measureText(String(to)).width;
        const lineW = (from ? fromW + arrowW + gapw * 2 : 0) + toW;
        let x = cfg.priceX === "center" ? W / 2 - lineW / 2 : rx;
        ctx.shadowColor = "rgba(0,0,0,.55)";
        ctx.shadowBlur = 6;
        ctx.shadowOffsetY = 2;
        if (from) {
          ctx.fillStyle = "#93AAA4"; // old price, dimmed
          ctx.fillText(from, x, ry);
          x += fromW + gapw;
          // vector arrow →
          const ax = x;
          const ac = lightenHex(accent, 0.2);
          ctx.save();
          ctx.shadowColor = "transparent";
          ctx.strokeStyle = ac;
          ctx.fillStyle = ac;
          ctx.lineWidth = Math.max(4, rfs * 0.08);
          ctx.lineCap = "round";
          ctx.beginPath();
          ctx.moveTo(ax, ry);
          ctx.lineTo(ax + arrowW - rfs * 0.28, ry);
          ctx.stroke();
          const hx = ax + arrowW; // arrowhead tip
          const hh = rfs * 0.2;
          ctx.beginPath();
          ctx.moveTo(hx, ry);
          ctx.lineTo(ax + arrowW - rfs * 0.3, ry - hh);
          ctx.lineTo(ax + arrowW - rfs * 0.3, ry + hh);
          ctx.closePath();
          ctx.fill();
          ctx.restore();
          x += arrowW + gapw;
        }
        ctx.fillStyle = accent; // new price, bright accent
        ctx.fillText(String(to), x, ry);
        ctx.shadowColor = "transparent";
        ctx.shadowBlur = 0;
        ctx.shadowOffsetY = 0;
      }
      // MCAP pill
      if (mcap) {
        const label = `MCAP ${mcap}`;
        const fsz = Number(cfg.metaFontSize) || 44;
        ctx.font = `600 ${fsz}px ${F.s}`;
        const chipH = fsz * 1.9;
        const r = Math.min(chipH / 2, fsz * 0.55);
        const padX = fsz * 0.7;
        const cy = Number(cfg.metaY) || 902;
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        const w = ctx.measureText(label).width + padX * 2;
        const x = cfg.metaX === "center" ? (W - w) / 2 : Number(cfg.metaX) || 262;
        ctx.beginPath();
        ctx.moveTo(x + r, cy);
        ctx.arcTo(x + w, cy, x + w, cy + chipH, r);
        ctx.arcTo(x + w, cy + chipH, x, cy + chipH, r);
        ctx.arcTo(x, cy + chipH, x, cy, r);
        ctx.arcTo(x, cy, x + w, cy, r);
        ctx.closePath();
        ctx.fillStyle = accent.startsWith("#") ? accent + "1A" : "rgba(51,229,201,.10)";
        ctx.fill();
        ctx.lineWidth = 2;
        ctx.strokeStyle = accent + "66";
        ctx.stroke();
        ctx.fillStyle = "#EAF6F2";
        ctx.fillText(label, x + w / 2, cy + chipH / 2 + 2);
      }
      ctx.textAlign = "left";
      ctx.textBaseline = "alphabetic";
    }

    // Pedestal badge — the small glass slab under the ring carries the tier
    // (listing) or the slot duration (trending) instead of sitting empty.
    if (badge && cfg.showBadge !== false && cfg.slotShape !== "rect") {
      const bfs = Number(cfg.badgeFontSize) || 30;
      ctx.font = `600 ${bfs}px ${F.s}`;
      ctx.letterSpacing = "4px";
      const btext = String(badge).toUpperCase().slice(0, 24);
      const bw = ctx.measureText(btext).width;
      const bx = (Number(cfg.badgeX) || W - 460) - bw / 2;
      const by = Number(cfg.badgeY) || H - 278;
      ctx.textBaseline = "middle";
      ctx.shadowColor = "rgba(0,0,0,.6)";
      ctx.shadowBlur = 6;
      ctx.shadowOffsetY = 1;
      ctx.fillStyle = "#D9F2EA";
      ctx.fillText(btext, bx, by);
      ctx.shadowColor = "transparent";
      ctx.shadowBlur = 0;
      ctx.shadowOffsetY = 0;
      ctx.letterSpacing = "0px";
      ctx.textBaseline = "alphabetic";
    }

    // Overlay mode → PNG WITH ALPHA (transparency preserved for ffmpeg compositing);
    // still mode → the normal send buffer (may be JPEG-flattened for size).
    return transparent ? canvas.toBuffer("image/png") : toSendBuffer(canvas);
  } catch (e) {
    log.warn(`[bannerTpl] compose(${kind}) failed: ${e.message}`);
    return null;
  }
}
// ── Animated fill-in: composite the token overlay (logo + $ticker + name + price/MC
// chips) onto an admin's EMPTY animated template (GIF/MP4), so the same auto-filled
// banner the still compositor makes also works animated. Returns { type:'animation',
// source: <mp4 buffer> } or null on ANY failure (caller falls back to the clip as-is).
let _FF;
function ffmpegLib() {
  if (_FF !== undefined) return _FF;
  try {
    const ffmpeg = require("fluent-ffmpeg");
    ffmpeg.setFfmpegPath(require("@ffmpeg-installer/ffmpeg").path);
    _FF = ffmpeg;
  } catch (e) {
    log.warn(`[bannerTpl] ffmpeg unavailable (animated fill-in disabled): ${e.message}`);
    _FF = null;
  }
  return _FF;
}
/**
 * Make an admin-uploaded clip PLAY INLINE in a channel.
 *
 * Telegram autoplays a clip only when it is an MP4. The official clients
 * convert GIF → MP4 *before* uploading; the server does not, and neither does
 * MTProto. So a raw .gif sent over GramJS lands as a FILE CARD —
 * "banner-media-rankup.gif · 783 KB" — which is exactly what the rank-up alert
 * looked like, while the trending post played fine because its clip goes
 * through composeOntoClip, whose ffmpeg step already outputs MP4.
 * DocumentAttributeAnimated (see gramjs.js) is necessary but NOT sufficient:
 * the container itself has to change.
 *
 * MP4 uploads go through the SAME conversion, because the container is only
 * half the problem. A clip whose extension is .mp4 was being sent with
 * sendVideo, which renders a player with a play button — the viewer has to tap
 * it, and it does not loop. That is a video, not a GIF, and it is what "the
 * banner ad is still a file" means in practice. The distinction Telegram makes
 * is not the extension but the AUDIO TRACK: strip it and mark the document
 * animated and the same MP4 autoplays, loops, and shows no controls. Every
 * template clip is therefore normalised to a silent MP4 and sent as an
 * animation — these are decorative loops above a post, never something anyone
 * wants to press play on.
 *
 * Conversions are cached in tmp under the source's mtime, so a clip is
 * re-encoded only after the admin uploads a new one — not once per alert.
 * Failure returns the original, so the worst case stays "posts as a file",
 * never "posts nothing".
 */
const CLIP_RE = /\.(gif|mp4|webm|mov)$/i;

async function toInlineClip(media) {
  if (!media || typeof media.source !== "string" || !CLIP_RE.test(media.source)) return media;
  const ffmpeg = ffmpegLib();
  const st = fss.existsSync(media.source) ? fss.statSync(media.source) : null;
  if (!ffmpeg || !st) {
    if (!ffmpeg) log.warn("[bannerTpl] clip→animation skipped (no ffmpeg) — it will post as a FILE CARD");
    return media;
  }
  const stem = path.basename(media.source).replace(CLIP_RE, "");
  const out = path.join(os.tmpdir(), `bt-clip-${stem}-${Math.round(st.mtimeMs)}.mp4`);
  if (exists(out)) return { type: "animation", source: out };
  try {
    await new Promise((resolve, reject) => {
      ffmpeg(media.source)
        // yuv420p + even dimensions is the combination every Telegram client can
        // decode; -an because an animation must be silent (a soundtrack makes
        // Telegram treat it as a video, with controls, not an autoplaying GIF).
        .outputOptions([
          "-movflags",
          "+faststart",
          "-pix_fmt",
          "yuv420p",
          "-vf",
          "scale=trunc(iw/2)*2:trunc(ih/2)*2",
          "-an",
          "-t",
          "20",
        ])
        .save(out)
        .on("end", resolve)
        .on("error", reject);
    });
    log.info(`[bannerTpl] clip→animation ✔ ${path.basename(media.source)} → ${path.basename(out)} (autoplays, loops, no controls)`);
    return { type: "animation", source: out };
  } catch (e) {
    // noise: fails open by design — the clip still posts, just as uploaded.
    // Babysitting lines like this were drowning the ops channel.
    log.noise(`[bannerTpl] clip→animation failed (${e.message}) — sending as-is (may post as a file card)`);
    fss.promises.unlink(out).catch(() => {});
    return media;
  }
}

async function composeOntoClip(kind, media, logoBuffer, data) {
  const ffmpeg = ffmpegLib();
  if (!ffmpeg || !media || !media.source) return null;
  let overlay;
  try { overlay = await compose(kind, logoBuffer, data, { transparent: true }); } catch (_) { overlay = null; }
  if (!overlay) return null;
  const dir = os.tmpdir();
  // Best-effort sweep of stale render files so temp doesn't grow unbounded.
  try {
    const now = Date.now();
    for (const f of await fss.promises.readdir(dir)) {
      if (!/^bt-(ov|out)-/.test(f)) continue;
      const fp = path.join(dir, f);
      const st = await fss.promises.stat(fp).catch(() => null);
      if (st && now - st.mtimeMs > 600000) fss.promises.unlink(fp).catch(() => {});
    }
  } catch (_) {}
  const stamp = `${process.pid}-${Date.now()}-${Math.floor(Math.random() * 1e6)}`;
  const ovPath = path.join(dir, `bt-ov-${stamp}.png`);
  const outPath = path.join(dir, `bt-out-${stamp}.mp4`);
  try {
    await fss.promises.writeFile(ovPath, overlay);
    await new Promise((resolve, reject) => {
      ffmpeg(media.source)
        .input(ovPath)
        // Normalize both to 1280×640 (a clean 2:1 Telegram size) and lay the token overlay
        // over every frame. Plain scale (no scale2ref) is the most portable across builds.
        .complexFilter("[0:v]scale=1280:640[bg];[1:v]scale=1280:640[ov];[bg][ov]overlay=0:0,format=yuv420p[vout]", "vout")
        .outputOptions(["-movflags", "+faststart", "-an", "-t", "20"]) // silent, ≤20s
        .save(outPath)
        .on("end", resolve)
        .on("error", reject);
    });
    fss.promises.unlink(ovPath).catch(() => {});
    // Return the .mp4 PATH (Telegram detects the type from the extension); the sweep above
    // reclaims it later. A Buffer would drop the filename and could be mis-detected.
    return { type: "animation", source: outPath };
  } catch (e) {
    log.warn(`[bannerTpl] composeOntoClip(${kind}) failed: ${e.message}`);
    fss.promises.unlink(ovPath).catch(() => {});
    fss.promises.unlink(outPath).catch(() => {});
    return null;
  }
}

// ── Editor backdrop: the layout editor needs a still image to draw the logo/text +
// guide boxes on. When only an animated template (GIF/MP4) is uploaded — no still
// artwork — we grab ONE frame of the clip and use it as the backdrop, so positioning
// happens against the real template look. Cached per clip identity (mtime+size) so
// repeated ± taps don't re-run ffmpeg.
const _frameCache = {}; // kind -> { key, buf }
// Drop a kind's cached clip frame so the next render re-extracts from the new clip
// (called on upload/removal). Hoisted, so saveMedia/removeMedia above can use it.
function _invalidateClipCache(kind) {
  delete _frameCache[kind];
}
async function clipFrame(kind) {
  const media = mediaOverride(kind);
  if (!media || !media.source) return null;
  const ffmpeg = ffmpegLib();
  if (!ffmpeg) return null;
  try {
    const st = await fss.promises.stat(media.source).catch(() => null);
    const key = st ? `${media.source}:${st.size}:${st.mtimeMs}` : media.source;
    if (_frameCache[kind] && _frameCache[kind].key === key) return _frameCache[kind].buf;
    const outPath = path.join(os.tmpdir(), `bt-frame-${process.pid}-${Date.now()}-${Math.floor(Math.random() * 1e6)}.png`);
    await new Promise((resolve, reject) => {
      ffmpeg(media.source)
        .outputOptions(["-frames:v", "1"]) // first frame only
        .save(outPath)
        .on("end", resolve)
        .on("error", reject);
    });
    const buf = await fss.promises.readFile(outPath);
    fss.promises.unlink(outPath).catch(() => {});
    _frameCache[kind] = { key, buf };
    return buf;
  } catch (e) {
    log.warn(`[bannerTpl] clipFrame(${kind}) failed: ${e.message}`);
    return null;
  }
}
function _paintPlaceholder(ctx, W, H) {
  const g = ctx.createLinearGradient(0, 0, W, H);
  g.addColorStop(0, "#0b1220");
  g.addColorStop(1, "#10201c");
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, W, H);
}
/** A still image for the layout editor / preview, matching what ACTUALLY posts:
 *  when an animated clip is set it WINS over the still artwork (postMedia does the
 *  same), so preview the overlay on a FRAME of that clip; otherwise composite on the
 *  still artwork; else a neutral backdrop. Returns a PNG Buffer or null. */
async function editorStill(kind, logoBuffer, data) {
  const hasClip = !!mediaOverride(kind);
  // Still artwork only when NO clip overrides it — else the preview would show the
  // bundled banner while real posts use the uploaded GIF (reported: "still using the
  // banner though I set the GIF").
  if (!hasClip && hasTemplate(kind)) return compose(kind, logoBuffer, data);
  const cv = canvasLib();
  if (!cv) return null;
  let overlay;
  try { overlay = await compose(kind, logoBuffer, data, { transparent: true }); } catch (_) { overlay = null; }
  if (!overlay) return null;
  try {
    const W = REF_W;
    const H = REF_H;
    const canvas = cv.createCanvas(W, H);
    const ctx = canvas.getContext("2d");
    const frame = await clipFrame(kind).catch(() => null);
    let drew = false;
    if (frame) {
      try { ctx.drawImage(await cv.loadImage(frame), 0, 0, W, H); drew = true; } catch (_) {}
    }
    if (!drew) _paintPlaceholder(ctx, W, H);
    ctx.drawImage(await cv.loadImage(overlay), 0, 0, W, H);
    return toSendBuffer(canvas);
  } catch (e) {
    log.warn(`[bannerTpl] editorStill(${kind}) failed: ${e.message}`);
    return null;
  }
}

/** One-line boot report so pm2 logs show the banner pipeline's health without
 *  needing a live purchase: canvas availability + which artwork each kind
 *  resolves to (uploaded / bundled / MISSING). */
function selfCheck() {
  const canvas = canvasLib() ? "OK" : "MISSING (run 'npm ci' in bot/)";
  const art = KINDS.map((k) => {
    const state = hasUploaded(k) ? "uploaded" : exists(bundledPath(k)) ? "bundled" : "MISSING";
    return `${k}=${state}`;
  }).join(" ");
  const line = `[bannerTpl] selfcheck: canvas=${canvas} artwork: ${art}`;
  if (canvas === "OK" && !art.includes("MISSING")) log.info(line);
  else log.warn(`${line} — channel posts will degrade until this is fixed`);
  return line;
}

async function saveTemplate(kind, buffer) {
  await fss.promises.mkdir(DATA_DIR, { recursive: true });
  await fss.promises.writeFile(uploadedPath(kind), buffer);
  mediaMirror.mirrorFile(path.basename(uploadedPath(kind))).catch(() => {});
}
/** Remove the admin upload — the bundled default artwork takes over again. */
async function removeTemplate(kind) {
  try {
    await fss.promises.unlink(uploadedPath(kind));
  } catch {
    /* already gone */
  }
  mediaMirror.deleteMirror(path.basename(uploadedPath(kind))).catch(() => {});
}

module.exports = {
  KINDS,
  compose,
  selfCheck,
  postingEnabled,
  setPostingEnabled,
  hasTemplate,
  hasUploaded,
  saveTemplate,
  removeTemplate,
  mediaOverride,
  composeOntoClip,
  toInlineClip,
  clipFrame,
  editorStill,
  saveMedia,
  removeMedia,
  hasMedia,
  getSettings,
  updateSettings,
  resetSettings,
  resolvePath,
  DEFAULTS,
  defaultsFor,
};
